export enum EstadoPedido {
  PENDIENTE = 'PENDIENTE',
  CONFIRMADO = 'CONFIRMADO',
  PREPARANDO = 'PREPARANDO',
  ENVIADO = 'ENVIADO',
  ENTREGADO = 'ENTREGADO',
  CANCELADO = 'CANCELADO',
}

export enum MetodoPago {
  TRANSFERENCIA = 'TRANSFERENCIA',
  TARJETA = 'TARJETA',
  EFECTIVO = 'EFECTIVO',
  OTRO = 'OTRO',
}